// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "DistCalc_DistCalcThread.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic DistCalc_DistCalcThread::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic DistCalc_DistCalcThread::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state2 = "10";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state3 = "100";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state4 = "1000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state5 = "10000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state6 = "100000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state7 = "1000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state8 = "10000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state9 = "100000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state10 = "1000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state11 = "10000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state12 = "100000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state45 = "100000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state46 = "1000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state47 = "10000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state48 = "100000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state49 = "1000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state50 = "10000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state51 = "100000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state52 = "1000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state53 = "10000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state54 = "100000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state55 = "1000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state56 = "10000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state57 = "100000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state58 = "1000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state59 = "10000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state60 = "100000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state61 = "1000000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state62 = "10000000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state63 = "100000000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state64 = "1000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state65 = "10000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state66 = "100000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state67 = "1000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state68 = "10000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state69 = "100000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state70 = "1000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state71 = "10000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state72 = "100000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state73 = "1000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state74 = "10000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state75 = "100000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state76 = "1000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<77> DistCalc_DistCalcThread::ap_ST_fsm_state77 = "10000000000000000000000000000000000000000000000000000000000000000000000000000";
const bool DistCalc_DistCalcThread::ap_const_boolean_1 = true;
const sc_lv<32> DistCalc_DistCalcThread::ap_const_lv32_1 = "1";
const sc_lv<1> DistCalc_DistCalcThread::ap_const_lv1_1 = "1";
const sc_lv<32> DistCalc_DistCalcThread::ap_const_lv32_2 = "10";
const sc_lv<32> DistCalc_DistCalcThread::ap_const_lv32_4 = "100";
const sc_lv<32> DistCalc_DistCalcThread::ap_const_lv32_5 = "101";
const sc_lv<32> DistCalc_DistCalcThread::ap_const_lv32_B = "1011";
const sc_lv<32> DistCalc_DistCalcThread::ap_const_lv32_44 = "1000100";
const sc_lv<32> DistCalc_DistCalcThread::ap_const_lv32_4C = "1001100";
const sc_lv<64> DistCalc_DistCalcThread::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<1> DistCalc_DistCalcThread::ap_const_lv1_0 = "0";
const sc_lv<32> DistCalc_DistCalcThread::ap_const_lv32_45 = "1000101";
const sc_lv<32> DistCalc_DistCalcThread::ap_const_lv32_6 = "110";
const sc_lv<32> DistCalc_DistCalcThread::ap_const_lv32_C = "1100";
const sc_lv<32> DistCalc_DistCalcThread::ap_const_lv32_3 = "11";

DistCalc_DistCalcThread::DistCalc_DistCalcThread(sc_module_name name) : sc_module(name), mVcdFile(0) {
    DistCalc_fptrunc_bkb_U0 = new DistCalc_fptrunc_bkb<1,1,64,32>("DistCalc_fptrunc_bkb_U0");
    DistCalc_fptrunc_bkb_U0->din0(totalDist_reg_119);
    DistCalc_fptrunc_bkb_U0->dout(v_fu_160_p1);
    DistCalc_dadd_64ncud_U1 = new DistCalc_dadd_64ncud<1,8,64,64,64>("DistCalc_dadd_64ncud_U1");
    DistCalc_dadd_64ncud_U1->clk(ap_clk);
    DistCalc_dadd_64ncud_U1->reset(ap_rst);
    DistCalc_dadd_64ncud_U1->din0(totalDist_reg_119);
    DistCalc_dadd_64ncud_U1->din1(tmp_3_reg_282);
    DistCalc_dadd_64ncud_U1->ce(ap_var_for_const0);
    DistCalc_dadd_64ncud_U1->dout(grp_fu_165_p2);
    DistCalc_sitodp_3dEe_U2 = new DistCalc_sitodp_3dEe<1,6,32,64>("DistCalc_sitodp_3dEe_U2");
    DistCalc_sitodp_3dEe_U2->clk(ap_clk);
    DistCalc_sitodp_3dEe_U2->reset(ap_rst);
    DistCalc_sitodp_3dEe_U2->din0(tmp_1_reg_272);
    DistCalc_sitodp_3dEe_U2->ce(ap_var_for_const0);
    DistCalc_sitodp_3dEe_U2->dout(grp_fu_170_p1);
    DistCalc_dsqrt_64eOg_U3 = new DistCalc_dsqrt_64eOg<1,57,64,64,64>("DistCalc_dsqrt_64eOg_U3");
    DistCalc_dsqrt_64eOg_U3->clk(ap_clk);
    DistCalc_dsqrt_64eOg_U3->reset(ap_rst);
    DistCalc_dsqrt_64eOg_U3->din0(ap_var_for_const1);
    DistCalc_dsqrt_64eOg_U3->din1(tmp_2_reg_277);
    DistCalc_dsqrt_64eOg_U3->ce(ap_var_for_const0);
    DistCalc_dsqrt_64eOg_U3->dout(grp_fu_173_p2);
    DistCalc_mul_32s_fYi_U4 = new DistCalc_mul_32s_fYi<1,2,32,32,32>("DistCalc_mul_32s_fYi_U4");
    DistCalc_mul_32s_fYi_U4->clk(ap_clk);
    DistCalc_mul_32s_fYi_U4->reset(ap_rst);
    DistCalc_mul_32s_fYi_U4->din0(tmp_7_reg_245);
    DistCalc_mul_32s_fYi_U4->din1(tmp_7_reg_245);
    DistCalc_mul_32s_fYi_U4->ce(ap_var_for_const0);
    DistCalc_mul_32s_fYi_U4->dout(grp_fu_201_p2);
    DistCalc_mul_32s_fYi_U5 = new DistCalc_mul_32s_fYi<1,2,32,32,32>("DistCalc_mul_32s_fYi_U5");
    DistCalc_mul_32s_fYi_U5->clk(ap_clk);
    DistCalc_mul_32s_fYi_U5->reset(ap_rst);
    DistCalc_mul_32s_fYi_U5->din0(tmp_9_reg_251);
    DistCalc_mul_32s_fYi_U5->din1(tmp_9_reg_251);
    DistCalc_mul_32s_fYi_U5->ce(ap_var_for_const0);
    DistCalc_mul_32s_fYi_U5->dout(grp_fu_205_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state69);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state70);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state77);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state2);
    sensitive << ( x1_empty_n );
    sensitive << ( y2_empty_n );
    sensitive << ( tmp_read_fu_88_p2 );

    SC_METHOD(thread_ap_block_state3);
    sensitive << ( x1_empty_n );
    sensitive << ( y2_empty_n );
    sensitive << ( ap_predicate_op115_read_state3 );

    SC_METHOD(thread_ap_predicate_op115_read_state3);
    sensitive << ( tmp_reg_213 );
    sensitive << ( tmp_4_fu_178_p2 );

    SC_METHOD(thread_i_1_fu_195_p2);
    sensitive << ( i_reg_149 );

    SC_METHOD(thread_outputDist);
    sensitive << ( x1_empty_n );
    sensitive << ( y2_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_reg_213 );
    sensitive << ( tmp_4_fu_178_p2 );
    sensitive << ( ap_predicate_op115_read_state3 );
    sensitive << ( v_fu_160_p1 );

    SC_METHOD(thread_outputDist_ap_vld);
    sensitive << ( x1_empty_n );
    sensitive << ( y2_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_reg_213 );
    sensitive << ( tmp_4_fu_178_p2 );
    sensitive << ( ap_predicate_op115_read_state3 );

    SC_METHOD(thread_tmp_1_fu_209_p2);
    sensitive << ( tmp_8_reg_262 );
    sensitive << ( tmp_s_reg_267 );

    SC_METHOD(thread_tmp_4_fu_178_p2);
    sensitive << ( x1_empty_n );
    sensitive << ( y2_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_reg_213 );
    sensitive << ( tmp_15_reg_217 );
    sensitive << ( ap_predicate_op115_read_state3 );
    sensitive << ( i_reg_149 );

    SC_METHOD(thread_tmp_7_fu_183_p2);
    sensitive << ( x1_dout );
    sensitive << ( x_reg_131 );

    SC_METHOD(thread_tmp_9_fu_189_p2);
    sensitive << ( y2_dout );
    sensitive << ( y_reg_140 );

    SC_METHOD(thread_tmp_read_fu_88_p2);
    sensitive << ( ready );
    sensitive << ( x1_empty_n );
    sensitive << ( y2_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_read_fu_88_p2 );

    SC_METHOD(thread_x1_blk_n);
    sensitive << ( x1_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_read_fu_88_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_reg_213 );
    sensitive << ( tmp_4_fu_178_p2 );

    SC_METHOD(thread_x1_read);
    sensitive << ( x1_empty_n );
    sensitive << ( y2_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_read_fu_88_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_predicate_op115_read_state3 );

    SC_METHOD(thread_y2_blk_n);
    sensitive << ( y2_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_read_fu_88_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_reg_213 );
    sensitive << ( tmp_4_fu_178_p2 );

    SC_METHOD(thread_y2_read);
    sensitive << ( x1_empty_n );
    sensitive << ( y2_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_read_fu_88_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_predicate_op115_read_state3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( x1_empty_n );
    sensitive << ( y2_empty_n );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_read_fu_88_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_reg_213 );
    sensitive << ( tmp_4_fu_178_p2 );
    sensitive << ( ap_predicate_op115_read_state3 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "00000000000000000000000000000000000000000000000000000000000000000000000000010";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "DistCalc_DistCalcThread_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, numberOfPoints, "(port)numberOfPoints");
    sc_trace(mVcdFile, ready, "(port)ready");
    sc_trace(mVcdFile, x1_dout, "(port)x1_dout");
    sc_trace(mVcdFile, x1_empty_n, "(port)x1_empty_n");
    sc_trace(mVcdFile, x1_read, "(port)x1_read");
    sc_trace(mVcdFile, y2_dout, "(port)y2_dout");
    sc_trace(mVcdFile, y2_empty_n, "(port)y2_empty_n");
    sc_trace(mVcdFile, y2_read, "(port)y2_read");
    sc_trace(mVcdFile, outputDist, "(port)outputDist");
    sc_trace(mVcdFile, outputDist_ap_vld, "(port)outputDist_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, x1_blk_n, "x1_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_read_fu_88_p2, "tmp_read_fu_88_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_reg_213, "tmp_reg_213");
    sc_trace(mVcdFile, tmp_4_fu_178_p2, "tmp_4_fu_178_p2");
    sc_trace(mVcdFile, y2_blk_n, "y2_blk_n");
    sc_trace(mVcdFile, ap_block_state2, "ap_block_state2");
    sc_trace(mVcdFile, tmp_15_reg_217, "tmp_15_reg_217");
    sc_trace(mVcdFile, tmp_18_reg_235, "tmp_18_reg_235");
    sc_trace(mVcdFile, ap_predicate_op115_read_state3, "ap_predicate_op115_read_state3");
    sc_trace(mVcdFile, ap_block_state3, "ap_block_state3");
    sc_trace(mVcdFile, tmp_19_reg_240, "tmp_19_reg_240");
    sc_trace(mVcdFile, tmp_7_fu_183_p2, "tmp_7_fu_183_p2");
    sc_trace(mVcdFile, tmp_7_reg_245, "tmp_7_reg_245");
    sc_trace(mVcdFile, tmp_9_fu_189_p2, "tmp_9_fu_189_p2");
    sc_trace(mVcdFile, tmp_9_reg_251, "tmp_9_reg_251");
    sc_trace(mVcdFile, i_1_fu_195_p2, "i_1_fu_195_p2");
    sc_trace(mVcdFile, i_1_reg_257, "i_1_reg_257");
    sc_trace(mVcdFile, grp_fu_201_p2, "grp_fu_201_p2");
    sc_trace(mVcdFile, tmp_8_reg_262, "tmp_8_reg_262");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, grp_fu_205_p2, "grp_fu_205_p2");
    sc_trace(mVcdFile, tmp_s_reg_267, "tmp_s_reg_267");
    sc_trace(mVcdFile, tmp_1_fu_209_p2, "tmp_1_fu_209_p2");
    sc_trace(mVcdFile, tmp_1_reg_272, "tmp_1_reg_272");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_fu_170_p1, "grp_fu_170_p1");
    sc_trace(mVcdFile, tmp_2_reg_277, "tmp_2_reg_277");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, grp_fu_173_p2, "grp_fu_173_p2");
    sc_trace(mVcdFile, tmp_3_reg_282, "tmp_3_reg_282");
    sc_trace(mVcdFile, ap_CS_fsm_state69, "ap_CS_fsm_state69");
    sc_trace(mVcdFile, grp_fu_165_p2, "grp_fu_165_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state77, "ap_CS_fsm_state77");
    sc_trace(mVcdFile, totalDist_reg_119, "totalDist_reg_119");
    sc_trace(mVcdFile, x_reg_131, "x_reg_131");
    sc_trace(mVcdFile, y_reg_140, "y_reg_140");
    sc_trace(mVcdFile, i_reg_149, "i_reg_149");
    sc_trace(mVcdFile, v_fu_160_p1, "v_fu_160_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state70, "ap_CS_fsm_state70");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

DistCalc_DistCalcThread::~DistCalc_DistCalcThread() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete DistCalc_fptrunc_bkb_U0;
    delete DistCalc_dadd_64ncud_U1;
    delete DistCalc_sitodp_3dEe_U2;
    delete DistCalc_dsqrt_64eOg_U3;
    delete DistCalc_mul_32s_fYi_U4;
    delete DistCalc_mul_32s_fYi_U5;
}

void DistCalc_DistCalcThread::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void DistCalc_DistCalcThread::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv64_0;
}

void DistCalc_DistCalcThread::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_0) {
        ap_CS_fsm = ap_ST_fsm_state2;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state77.read())) {
        i_reg_149 = i_1_reg_257.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
                !((esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, x1_empty_n.read())) || (esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, y2_empty_n.read()))))) {
        i_reg_149 = ap_const_lv32_1;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state77.read())) {
        totalDist_reg_119 = grp_fu_165_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
                !((esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, x1_empty_n.read())) || (esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, y2_empty_n.read()))))) {
        totalDist_reg_119 = ap_const_lv64_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state77.read())) {
        x_reg_131 = tmp_18_reg_235.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
                !((esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, x1_empty_n.read())) || (esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, y2_empty_n.read()))))) {
        x_reg_131 = x1_dout.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state77.read())) {
        y_reg_140 = tmp_19_reg_240.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
                !((esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, x1_empty_n.read())) || (esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, y2_empty_n.read()))))) {
        y_reg_140 = y2_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op115_read_state3.read()) && !((esl_seteq<1,1,1>(ap_const_logic_0, x1_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op115_read_state3.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, y2_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op115_read_state3.read()))))) {
        i_1_reg_257 = i_1_fu_195_p2.read();
        tmp_18_reg_235 = x1_dout.read();
        tmp_19_reg_240 = y2_dout.read();
        tmp_7_reg_245 = tmp_7_fu_183_p2.read();
        tmp_9_reg_251 = tmp_9_fu_189_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && !((esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, x1_empty_n.read())) || (esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, y2_empty_n.read()))))) {
        tmp_15_reg_217 = numberOfPoints.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        tmp_1_reg_272 = tmp_1_fu_209_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        tmp_2_reg_277 = grp_fu_170_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state69.read())) {
        tmp_3_reg_282 = grp_fu_173_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        tmp_8_reg_262 = grp_fu_201_p2.read();
        tmp_s_reg_267 = grp_fu_205_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !((esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, x1_empty_n.read())) || (esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, y2_empty_n.read()))))) {
        tmp_reg_213 =  (sc_lv<1>) (ready.read());
    }
}

void DistCalc_DistCalcThread::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void DistCalc_DistCalcThread::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void DistCalc_DistCalcThread::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void DistCalc_DistCalcThread::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void DistCalc_DistCalcThread::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void DistCalc_DistCalcThread::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void DistCalc_DistCalcThread::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void DistCalc_DistCalcThread::thread_ap_CS_fsm_state69() {
    ap_CS_fsm_state69 = ap_CS_fsm.read()[68];
}

void DistCalc_DistCalcThread::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void DistCalc_DistCalcThread::thread_ap_CS_fsm_state70() {
    ap_CS_fsm_state70 = ap_CS_fsm.read()[69];
}

void DistCalc_DistCalcThread::thread_ap_CS_fsm_state77() {
    ap_CS_fsm_state77 = ap_CS_fsm.read()[76];
}

void DistCalc_DistCalcThread::thread_ap_block_state2() {
    ap_block_state2 = ((esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, x1_empty_n.read())) || (esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, y2_empty_n.read())));
}

void DistCalc_DistCalcThread::thread_ap_block_state3() {
    ap_block_state3 = ((esl_seteq<1,1,1>(ap_const_logic_0, x1_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op115_read_state3.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, y2_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op115_read_state3.read())));
}

void DistCalc_DistCalcThread::thread_ap_predicate_op115_read_state3() {
    ap_predicate_op115_read_state3 = (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_213.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_4_fu_178_p2.read()));
}

void DistCalc_DistCalcThread::thread_i_1_fu_195_p2() {
    i_1_fu_195_p2 = (!i_reg_149.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(i_reg_149.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void DistCalc_DistCalcThread::thread_outputDist() {
    outputDist = v_fu_160_p1.read();
}

void DistCalc_DistCalcThread::thread_outputDist_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_213.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_0, x1_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op115_read_state3.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, y2_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op115_read_state3.read()))) && 
         esl_seteq<1,1,1>(tmp_4_fu_178_p2.read(), ap_const_lv1_0))) {
        outputDist_ap_vld = ap_const_logic_1;
    } else {
        outputDist_ap_vld = ap_const_logic_0;
    }
}

void DistCalc_DistCalcThread::thread_tmp_1_fu_209_p2() {
    tmp_1_fu_209_p2 = (!tmp_s_reg_267.read().is_01() || !tmp_8_reg_262.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_s_reg_267.read()) + sc_biguint<32>(tmp_8_reg_262.read()));
}

void DistCalc_DistCalcThread::thread_tmp_4_fu_178_p2() {
    tmp_4_fu_178_p2 = (!i_reg_149.read().is_01() || !tmp_15_reg_217.read().is_01())? sc_lv<1>(): (sc_biguint<32>(i_reg_149.read()) < sc_biguint<32>(tmp_15_reg_217.read()));
}

void DistCalc_DistCalcThread::thread_tmp_7_fu_183_p2() {
    tmp_7_fu_183_p2 = (!x1_dout.read().is_01() || !x_reg_131.read().is_01())? sc_lv<32>(): (sc_biguint<32>(x1_dout.read()) - sc_biguint<32>(x_reg_131.read()));
}

void DistCalc_DistCalcThread::thread_tmp_9_fu_189_p2() {
    tmp_9_fu_189_p2 = (!y2_dout.read().is_01() || !y_reg_140.read().is_01())? sc_lv<32>(): (sc_biguint<32>(y2_dout.read()) - sc_biguint<32>(y_reg_140.read()));
}

void DistCalc_DistCalcThread::thread_tmp_read_fu_88_p2() {
    tmp_read_fu_88_p2 =  (sc_lv<1>) (ready.read());
}

void DistCalc_DistCalcThread::thread_x1_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_213.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_4_fu_178_p2.read())))) {
        x1_blk_n = x1_empty_n.read();
    } else {
        x1_blk_n = ap_const_logic_1;
    }
}

void DistCalc_DistCalcThread::thread_x1_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
          !((esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, x1_empty_n.read())) || (esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, y2_empty_n.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op115_read_state3.read()) && 
          !((esl_seteq<1,1,1>(ap_const_logic_0, x1_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op115_read_state3.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, y2_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op115_read_state3.read())))))) {
        x1_read = ap_const_logic_1;
    } else {
        x1_read = ap_const_logic_0;
    }
}

void DistCalc_DistCalcThread::thread_y2_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_213.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_4_fu_178_p2.read())))) {
        y2_blk_n = y2_empty_n.read();
    } else {
        y2_blk_n = ap_const_logic_1;
    }
}

void DistCalc_DistCalcThread::thread_y2_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
          !((esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, x1_empty_n.read())) || (esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, y2_empty_n.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op115_read_state3.read()) && 
          !((esl_seteq<1,1,1>(ap_const_logic_0, x1_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op115_read_state3.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, y2_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op115_read_state3.read())))))) {
        y2_read = ap_const_logic_1;
    } else {
        y2_read = ap_const_logic_0;
    }
}

void DistCalc_DistCalcThread::thread_ap_NS_fsm() {
    if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state2))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !((esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, x1_empty_n.read())) || (esl_seteq<1,1,1>(tmp_read_fu_88_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, y2_empty_n.read()))))) {
            ap_NS_fsm = ap_ST_fsm_state3;
        } else {
            ap_NS_fsm = ap_ST_fsm_state2;
        }
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state3))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && !((esl_seteq<1,1,1>(ap_const_logic_0, x1_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op115_read_state3.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, y2_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op115_read_state3.read()))) && (esl_seteq<1,1,1>(tmp_4_fu_178_p2.read(), ap_const_lv1_0) || 
  esl_seteq<1,1,1>(tmp_reg_213.read(), ap_const_lv1_0)))) {
            ap_NS_fsm = ap_ST_fsm_state2;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_213.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_4_fu_178_p2.read()) && !((esl_seteq<1,1,1>(ap_const_logic_0, x1_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op115_read_state3.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, y2_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op115_read_state3.read()))))) {
            ap_NS_fsm = ap_ST_fsm_state4;
        } else {
            ap_NS_fsm = ap_ST_fsm_state3;
        }
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state4))
    {
        ap_NS_fsm = ap_ST_fsm_state5;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state5))
    {
        ap_NS_fsm = ap_ST_fsm_state6;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state6))
    {
        ap_NS_fsm = ap_ST_fsm_state7;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state7))
    {
        ap_NS_fsm = ap_ST_fsm_state8;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state8))
    {
        ap_NS_fsm = ap_ST_fsm_state9;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state9))
    {
        ap_NS_fsm = ap_ST_fsm_state10;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state10))
    {
        ap_NS_fsm = ap_ST_fsm_state11;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state11))
    {
        ap_NS_fsm = ap_ST_fsm_state12;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state12))
    {
        ap_NS_fsm = ap_ST_fsm_state13;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state13))
    {
        ap_NS_fsm = ap_ST_fsm_state14;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state14))
    {
        ap_NS_fsm = ap_ST_fsm_state15;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state15))
    {
        ap_NS_fsm = ap_ST_fsm_state16;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state16))
    {
        ap_NS_fsm = ap_ST_fsm_state17;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state17))
    {
        ap_NS_fsm = ap_ST_fsm_state18;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state18))
    {
        ap_NS_fsm = ap_ST_fsm_state19;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state19))
    {
        ap_NS_fsm = ap_ST_fsm_state20;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state20))
    {
        ap_NS_fsm = ap_ST_fsm_state21;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state21))
    {
        ap_NS_fsm = ap_ST_fsm_state22;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state22))
    {
        ap_NS_fsm = ap_ST_fsm_state23;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state23))
    {
        ap_NS_fsm = ap_ST_fsm_state24;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state24))
    {
        ap_NS_fsm = ap_ST_fsm_state25;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state25))
    {
        ap_NS_fsm = ap_ST_fsm_state26;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state26))
    {
        ap_NS_fsm = ap_ST_fsm_state27;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state27))
    {
        ap_NS_fsm = ap_ST_fsm_state28;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state28))
    {
        ap_NS_fsm = ap_ST_fsm_state29;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state29))
    {
        ap_NS_fsm = ap_ST_fsm_state30;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state30))
    {
        ap_NS_fsm = ap_ST_fsm_state31;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state31))
    {
        ap_NS_fsm = ap_ST_fsm_state32;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state32))
    {
        ap_NS_fsm = ap_ST_fsm_state33;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state33))
    {
        ap_NS_fsm = ap_ST_fsm_state34;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state34))
    {
        ap_NS_fsm = ap_ST_fsm_state35;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state35))
    {
        ap_NS_fsm = ap_ST_fsm_state36;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state36))
    {
        ap_NS_fsm = ap_ST_fsm_state37;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state37))
    {
        ap_NS_fsm = ap_ST_fsm_state38;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state38))
    {
        ap_NS_fsm = ap_ST_fsm_state39;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state39))
    {
        ap_NS_fsm = ap_ST_fsm_state40;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state40))
    {
        ap_NS_fsm = ap_ST_fsm_state41;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state41))
    {
        ap_NS_fsm = ap_ST_fsm_state42;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state42))
    {
        ap_NS_fsm = ap_ST_fsm_state43;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state43))
    {
        ap_NS_fsm = ap_ST_fsm_state44;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state44))
    {
        ap_NS_fsm = ap_ST_fsm_state45;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state45))
    {
        ap_NS_fsm = ap_ST_fsm_state46;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state46))
    {
        ap_NS_fsm = ap_ST_fsm_state47;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state47))
    {
        ap_NS_fsm = ap_ST_fsm_state48;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state48))
    {
        ap_NS_fsm = ap_ST_fsm_state49;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state49))
    {
        ap_NS_fsm = ap_ST_fsm_state50;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state50))
    {
        ap_NS_fsm = ap_ST_fsm_state51;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state51))
    {
        ap_NS_fsm = ap_ST_fsm_state52;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state52))
    {
        ap_NS_fsm = ap_ST_fsm_state53;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state53))
    {
        ap_NS_fsm = ap_ST_fsm_state54;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state54))
    {
        ap_NS_fsm = ap_ST_fsm_state55;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state55))
    {
        ap_NS_fsm = ap_ST_fsm_state56;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state56))
    {
        ap_NS_fsm = ap_ST_fsm_state57;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state57))
    {
        ap_NS_fsm = ap_ST_fsm_state58;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state58))
    {
        ap_NS_fsm = ap_ST_fsm_state59;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state59))
    {
        ap_NS_fsm = ap_ST_fsm_state60;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state60))
    {
        ap_NS_fsm = ap_ST_fsm_state61;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state61))
    {
        ap_NS_fsm = ap_ST_fsm_state62;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state62))
    {
        ap_NS_fsm = ap_ST_fsm_state63;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state63))
    {
        ap_NS_fsm = ap_ST_fsm_state64;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state64))
    {
        ap_NS_fsm = ap_ST_fsm_state65;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state65))
    {
        ap_NS_fsm = ap_ST_fsm_state66;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state66))
    {
        ap_NS_fsm = ap_ST_fsm_state67;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state67))
    {
        ap_NS_fsm = ap_ST_fsm_state68;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state68))
    {
        ap_NS_fsm = ap_ST_fsm_state69;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state69))
    {
        ap_NS_fsm = ap_ST_fsm_state70;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state70))
    {
        ap_NS_fsm = ap_ST_fsm_state71;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state71))
    {
        ap_NS_fsm = ap_ST_fsm_state72;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state72))
    {
        ap_NS_fsm = ap_ST_fsm_state73;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state73))
    {
        ap_NS_fsm = ap_ST_fsm_state74;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state74))
    {
        ap_NS_fsm = ap_ST_fsm_state75;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state75))
    {
        ap_NS_fsm = ap_ST_fsm_state76;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state76))
    {
        ap_NS_fsm = ap_ST_fsm_state77;
    }
    else if (esl_seteq<1,77,77>(ap_CS_fsm.read(), ap_ST_fsm_state77))
    {
        ap_NS_fsm = ap_ST_fsm_state3;
    }
    else
    {
        ap_NS_fsm = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}
}

