// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _DistCalc_DistCalcThread_HH_
#define _DistCalc_DistCalcThread_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "DistCalc_fptrunc_bkb.h"
#include "DistCalc_dadd_64ncud.h"
#include "DistCalc_sitodp_3dEe.h"
#include "DistCalc_dsqrt_64eOg.h"
#include "DistCalc_mul_32s_fYi.h"

namespace ap_rtl {

struct DistCalc_DistCalcThread : public sc_module {
    // Port declarations 12
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<32> > numberOfPoints;
    sc_in< sc_logic > ready;
    sc_in< sc_lv<32> > x1_dout;
    sc_in< sc_logic > x1_empty_n;
    sc_out< sc_logic > x1_read;
    sc_in< sc_lv<32> > y2_dout;
    sc_in< sc_logic > y2_empty_n;
    sc_out< sc_logic > y2_read;
    sc_out< sc_lv<32> > outputDist;
    sc_out< sc_logic > outputDist_ap_vld;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<64> > ap_var_for_const1;


    // Module declarations
    DistCalc_DistCalcThread(sc_module_name name);
    SC_HAS_PROCESS(DistCalc_DistCalcThread);

    ~DistCalc_DistCalcThread();

    sc_trace_file* mVcdFile;

    DistCalc_fptrunc_bkb<1,1,64,32>* DistCalc_fptrunc_bkb_U0;
    DistCalc_dadd_64ncud<1,8,64,64,64>* DistCalc_dadd_64ncud_U1;
    DistCalc_sitodp_3dEe<1,6,32,64>* DistCalc_sitodp_3dEe_U2;
    DistCalc_dsqrt_64eOg<1,57,64,64,64>* DistCalc_dsqrt_64eOg_U3;
    DistCalc_mul_32s_fYi<1,2,32,32,32>* DistCalc_mul_32s_fYi_U4;
    DistCalc_mul_32s_fYi<1,2,32,32,32>* DistCalc_mul_32s_fYi_U5;
    sc_signal< sc_logic > x1_blk_n;
    sc_signal< sc_lv<77> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > tmp_read_fu_88_p2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > tmp_reg_213;
    sc_signal< sc_lv<1> > tmp_4_fu_178_p2;
    sc_signal< sc_logic > y2_blk_n;
    sc_signal< bool > ap_block_state2;
    sc_signal< sc_lv<32> > tmp_15_reg_217;
    sc_signal< sc_lv<32> > tmp_18_reg_235;
    sc_signal< bool > ap_predicate_op115_read_state3;
    sc_signal< bool > ap_block_state3;
    sc_signal< sc_lv<32> > tmp_19_reg_240;
    sc_signal< sc_lv<32> > tmp_7_fu_183_p2;
    sc_signal< sc_lv<32> > tmp_7_reg_245;
    sc_signal< sc_lv<32> > tmp_9_fu_189_p2;
    sc_signal< sc_lv<32> > tmp_9_reg_251;
    sc_signal< sc_lv<32> > i_1_fu_195_p2;
    sc_signal< sc_lv<32> > i_1_reg_257;
    sc_signal< sc_lv<32> > grp_fu_201_p2;
    sc_signal< sc_lv<32> > tmp_8_reg_262;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<32> > grp_fu_205_p2;
    sc_signal< sc_lv<32> > tmp_s_reg_267;
    sc_signal< sc_lv<32> > tmp_1_fu_209_p2;
    sc_signal< sc_lv<32> > tmp_1_reg_272;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<64> > grp_fu_170_p1;
    sc_signal< sc_lv<64> > tmp_2_reg_277;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<64> > grp_fu_173_p2;
    sc_signal< sc_lv<64> > tmp_3_reg_282;
    sc_signal< sc_logic > ap_CS_fsm_state69;
    sc_signal< sc_lv<64> > grp_fu_165_p2;
    sc_signal< sc_logic > ap_CS_fsm_state77;
    sc_signal< sc_lv<64> > totalDist_reg_119;
    sc_signal< sc_lv<32> > x_reg_131;
    sc_signal< sc_lv<32> > y_reg_140;
    sc_signal< sc_lv<32> > i_reg_149;
    sc_signal< sc_lv<32> > v_fu_160_p1;
    sc_signal< sc_logic > ap_CS_fsm_state70;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<77> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<77> ap_ST_fsm_state2;
    static const sc_lv<77> ap_ST_fsm_state3;
    static const sc_lv<77> ap_ST_fsm_state4;
    static const sc_lv<77> ap_ST_fsm_state5;
    static const sc_lv<77> ap_ST_fsm_state6;
    static const sc_lv<77> ap_ST_fsm_state7;
    static const sc_lv<77> ap_ST_fsm_state8;
    static const sc_lv<77> ap_ST_fsm_state9;
    static const sc_lv<77> ap_ST_fsm_state10;
    static const sc_lv<77> ap_ST_fsm_state11;
    static const sc_lv<77> ap_ST_fsm_state12;
    static const sc_lv<77> ap_ST_fsm_state13;
    static const sc_lv<77> ap_ST_fsm_state14;
    static const sc_lv<77> ap_ST_fsm_state15;
    static const sc_lv<77> ap_ST_fsm_state16;
    static const sc_lv<77> ap_ST_fsm_state17;
    static const sc_lv<77> ap_ST_fsm_state18;
    static const sc_lv<77> ap_ST_fsm_state19;
    static const sc_lv<77> ap_ST_fsm_state20;
    static const sc_lv<77> ap_ST_fsm_state21;
    static const sc_lv<77> ap_ST_fsm_state22;
    static const sc_lv<77> ap_ST_fsm_state23;
    static const sc_lv<77> ap_ST_fsm_state24;
    static const sc_lv<77> ap_ST_fsm_state25;
    static const sc_lv<77> ap_ST_fsm_state26;
    static const sc_lv<77> ap_ST_fsm_state27;
    static const sc_lv<77> ap_ST_fsm_state28;
    static const sc_lv<77> ap_ST_fsm_state29;
    static const sc_lv<77> ap_ST_fsm_state30;
    static const sc_lv<77> ap_ST_fsm_state31;
    static const sc_lv<77> ap_ST_fsm_state32;
    static const sc_lv<77> ap_ST_fsm_state33;
    static const sc_lv<77> ap_ST_fsm_state34;
    static const sc_lv<77> ap_ST_fsm_state35;
    static const sc_lv<77> ap_ST_fsm_state36;
    static const sc_lv<77> ap_ST_fsm_state37;
    static const sc_lv<77> ap_ST_fsm_state38;
    static const sc_lv<77> ap_ST_fsm_state39;
    static const sc_lv<77> ap_ST_fsm_state40;
    static const sc_lv<77> ap_ST_fsm_state41;
    static const sc_lv<77> ap_ST_fsm_state42;
    static const sc_lv<77> ap_ST_fsm_state43;
    static const sc_lv<77> ap_ST_fsm_state44;
    static const sc_lv<77> ap_ST_fsm_state45;
    static const sc_lv<77> ap_ST_fsm_state46;
    static const sc_lv<77> ap_ST_fsm_state47;
    static const sc_lv<77> ap_ST_fsm_state48;
    static const sc_lv<77> ap_ST_fsm_state49;
    static const sc_lv<77> ap_ST_fsm_state50;
    static const sc_lv<77> ap_ST_fsm_state51;
    static const sc_lv<77> ap_ST_fsm_state52;
    static const sc_lv<77> ap_ST_fsm_state53;
    static const sc_lv<77> ap_ST_fsm_state54;
    static const sc_lv<77> ap_ST_fsm_state55;
    static const sc_lv<77> ap_ST_fsm_state56;
    static const sc_lv<77> ap_ST_fsm_state57;
    static const sc_lv<77> ap_ST_fsm_state58;
    static const sc_lv<77> ap_ST_fsm_state59;
    static const sc_lv<77> ap_ST_fsm_state60;
    static const sc_lv<77> ap_ST_fsm_state61;
    static const sc_lv<77> ap_ST_fsm_state62;
    static const sc_lv<77> ap_ST_fsm_state63;
    static const sc_lv<77> ap_ST_fsm_state64;
    static const sc_lv<77> ap_ST_fsm_state65;
    static const sc_lv<77> ap_ST_fsm_state66;
    static const sc_lv<77> ap_ST_fsm_state67;
    static const sc_lv<77> ap_ST_fsm_state68;
    static const sc_lv<77> ap_ST_fsm_state69;
    static const sc_lv<77> ap_ST_fsm_state70;
    static const sc_lv<77> ap_ST_fsm_state71;
    static const sc_lv<77> ap_ST_fsm_state72;
    static const sc_lv<77> ap_ST_fsm_state73;
    static const sc_lv<77> ap_ST_fsm_state74;
    static const sc_lv<77> ap_ST_fsm_state75;
    static const sc_lv<77> ap_ST_fsm_state76;
    static const sc_lv<77> ap_ST_fsm_state77;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_44;
    static const sc_lv<32> ap_const_lv32_4C;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_45;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_3;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state69();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state70();
    void thread_ap_CS_fsm_state77();
    void thread_ap_block_state2();
    void thread_ap_block_state3();
    void thread_ap_predicate_op115_read_state3();
    void thread_i_1_fu_195_p2();
    void thread_outputDist();
    void thread_outputDist_ap_vld();
    void thread_tmp_1_fu_209_p2();
    void thread_tmp_4_fu_178_p2();
    void thread_tmp_7_fu_183_p2();
    void thread_tmp_9_fu_189_p2();
    void thread_tmp_read_fu_88_p2();
    void thread_x1_blk_n();
    void thread_x1_read();
    void thread_y2_blk_n();
    void thread_y2_read();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
