// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// slv0
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : reserved
// 0x14 : Data signal of numberOfPoints
//        bit 31~0 - numberOfPoints[31:0] (Read/Write)
// 0x18 : reserved
// 0x1c : Data signal of ready
//        bit 0  - ready[0] (Read/Write)
//        others - reserved
// 0x20 : reserved
// 0x24 : Data signal of outputDist
//        bit 31~0 - outputDist[31:0] (Read)
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDISTCALC_SLV0_ADDR_NUMBEROFPOINTS_DATA 0x14
#define XDISTCALC_SLV0_BITS_NUMBEROFPOINTS_DATA 32
#define XDISTCALC_SLV0_ADDR_READY_DATA          0x1c
#define XDISTCALC_SLV0_BITS_READY_DATA          1
#define XDISTCALC_SLV0_ADDR_OUTPUTDIST_DATA     0x24
#define XDISTCALC_SLV0_BITS_OUTPUTDIST_DATA     32

