// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdistcalc.h"

extern XDistcalc_Config XDistcalc_ConfigTable[];

XDistcalc_Config *XDistcalc_LookupConfig(u16 DeviceId) {
	XDistcalc_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDISTCALC_NUM_INSTANCES; Index++) {
		if (XDistcalc_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDistcalc_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDistcalc_Initialize(XDistcalc *InstancePtr, u16 DeviceId) {
	XDistcalc_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDistcalc_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDistcalc_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

