// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xdistcalc.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XDistcalc_CfgInitialize(XDistcalc *InstancePtr, XDistcalc_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Slv0_BaseAddress = ConfigPtr->Slv0_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XDistcalc_SetNumberofpoints(XDistcalc *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDistcalc_WriteReg(InstancePtr->Slv0_BaseAddress, XDISTCALC_SLV0_ADDR_NUMBEROFPOINTS_DATA, Data);
}

u32 XDistcalc_GetNumberofpoints(XDistcalc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDistcalc_ReadReg(InstancePtr->Slv0_BaseAddress, XDISTCALC_SLV0_ADDR_NUMBEROFPOINTS_DATA);
    return Data;
}

void XDistcalc_SetReady(XDistcalc *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDistcalc_WriteReg(InstancePtr->Slv0_BaseAddress, XDISTCALC_SLV0_ADDR_READY_DATA, Data);
}

u32 XDistcalc_GetReady(XDistcalc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDistcalc_ReadReg(InstancePtr->Slv0_BaseAddress, XDISTCALC_SLV0_ADDR_READY_DATA);
    return Data;
}

u32 XDistcalc_GetOutputdist(XDistcalc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDistcalc_ReadReg(InstancePtr->Slv0_BaseAddress, XDISTCALC_SLV0_ADDR_OUTPUTDIST_DATA);
    return Data;
}

